# Generated by Django 5.1 on 2026-04-03 12:54

import django.db.models.deletion
import invoicing_app.core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("taxes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.CharField(
                        db_index=True,
                        default=invoicing_app.core.models.generate_uuid,
                        editable=False,
                        help_text="External API reference (UUID4)",
                        max_length=36,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Soft delete flag"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Client's business or full name",
                        max_length=255,
                    ),
                ),
                (
                    "client_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("business", "Business"),
                        ],
                        db_index=True,
                        default="individual",
                        help_text="Individual or business for KRA classification",
                        max_length=20,
                    ),
                ),
                (
                    "business_registration_number",
                    models.CharField(
                        blank=True,
                        help_text="Business registration number if applicable",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="KRA PIN or VAT number",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Client's primary email",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Client's primary phone",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("KES", "Kenyan Shilling"), ("USD", "US Dollar")],
                        default="KES",
                        help_text="Default currency for invoices",
                        max_length=3,
                    ),
                ),
                (
                    "payment_terms_days",
                    models.IntegerField(
                        default=30, help_text="Invoice due-in days (payment terms)"
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Credit limit for future credit management",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about client", null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this client",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_clients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "default_tax_rate",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default VAT rate for this client",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="taxes.taxrate",
                    ),
                ),
            ],
            options={
                "db_table": "clients_client",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ClientAddress",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("billing", "Billing Address"),
                            ("shipping", "Shipping Address"),
                            ("other", "Other"),
                        ],
                        default="billing",
                        help_text="Type of address",
                        max_length=20,
                    ),
                ),
                (
                    "street_1",
                    models.CharField(help_text="Street line 1", max_length=255),
                ),
                (
                    "street_2",
                    models.CharField(
                        blank=True,
                        help_text="Street line 2 (apartment, suite, etc.)",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("city", models.CharField(help_text="City", max_length=100)),
                (
                    "state_province",
                    models.CharField(
                        blank=True,
                        help_text="State or province",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, help_text="Postal code", max_length=20, null=True
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="Kenya", help_text="Country", max_length=100
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the primary address of this type?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Client this address belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "db_table": "clients_clientaddress",
            },
        ),
        migrations.CreateModel(
            name="ClientContact",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(help_text="Contact person's name", max_length=255),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Job title (Finance Manager, etc.)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Contact email", max_length=254, null=True
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Contact phone", max_length=20, null=True
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Is this the primary contact?"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notes about this contact", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Client this contact belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "db_table": "clients_clientcontact",
            },
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["name"], name="clients_cli_name_5ab7bc_idx"),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["tax_id"], name="clients_cli_tax_id_f962f3_idx"),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["email"], name="clients_cli_email_56b9fc_idx"),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["is_active"], name="clients_cli_is_acti_57c1e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["client_type"], name="clients_cli_client__1e0f73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientaddress",
            index=models.Index(
                fields=["client", "address_type"], name="clients_cli_client__2484c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientaddress",
            index=models.Index(
                fields=["client", "is_primary"], name="clients_cli_client__5d11bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientcontact",
            index=models.Index(
                fields=["client"], name="clients_cli_client__3e31d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientcontact",
            index=models.Index(
                fields=["client", "is_primary"], name="clients_cli_client__b632ac_idx"
            ),
        ),
    ]
