# Generated by Django 5.1 on 2026-04-03 12:53

import django.db.models.deletion
import invoicing_app.core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanySettings",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created",
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "company_name",
                    models.CharField(
                        default="Your Company Name",
                        help_text="Official company name",
                        max_length=255,
                    ),
                ),
                (
                    "company_website",
                    models.URLField(
                        blank=True, help_text="Company website URL", null=True
                    ),
                ),
                (
                    "company_logo",
                    models.ImageField(
                        blank=True,
                        help_text="Company logo image (PNG/JPG, max 2MB, recommended 300x150px)",
                        null=True,
                        upload_to="company/",
                    ),
                ),
                (
                    "company_email",
                    models.EmailField(
                        default="info@yourcompany.com",
                        help_text="Primary contact email address",
                        max_length=254,
                    ),
                ),
                (
                    "company_phone",
                    models.CharField(
                        default="+1-234-567-8900",
                        help_text="Primary phone number",
                        max_length=20,
                    ),
                ),
                (
                    "company_address",
                    models.TextField(
                        default="123 Business St, City, Country",
                        help_text="Full company address",
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        help_text="Tax ID / VAT Registration Number (e.g., KRA PIN for Kenya)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "invoice_prefix",
                    models.CharField(
                        default="INV",
                        help_text="Prefix for invoice numbers (e.g., INV-2026-0001)",
                        max_length=10,
                    ),
                ),
                (
                    "payment_prefix",
                    models.CharField(
                        default="REC",
                        help_text="Prefix for payment receipt numbers (e.g., REC-2026-0001)",
                        max_length=10,
                    ),
                ),
                (
                    "quote_prefix",
                    models.CharField(
                        default="QUOTE",
                        help_text="Prefix for quotation numbers (e.g., QUOTE-2026-0001)",
                        max_length=10,
                    ),
                ),
                (
                    "delivery_prefix",
                    models.CharField(
                        default="DLV",
                        help_text="Prefix for delivery challan numbers (e.g., DLV-2026-0001)",
                        max_length=10,
                    ),
                ),
                (
                    "financial_year_start",
                    models.IntegerField(
                        default=1,
                        help_text="Month number when financial year starts (1-12)",
                    ),
                ),
                (
                    "default_payment_terms",
                    models.CharField(
                        blank=True,
                        default="Payment due within 14 days of invoice date",
                        help_text="Default payment terms for invoices (e.g., Net 30 days)",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "bank_account_name",
                    models.CharField(
                        blank=True,
                        help_text="Bank account holder name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "bank_account_number",
                    models.CharField(
                        blank=True,
                        help_text="Bank account number",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, help_text="Bank name", max_length=255, null=True
                    ),
                ),
                (
                    "bank_branch",
                    models.CharField(
                        blank=True,
                        help_text="Bank branch (optional)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "bank_swift_code",
                    models.CharField(
                        blank=True,
                        help_text="SWIFT code (optional, for international transfers)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "bank_iban",
                    models.CharField(
                        blank=True,
                        help_text="IBAN (optional, for international transfers)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "mpesa_paybill_number",
                    models.CharField(
                        blank=True,
                        help_text="M-Pesa Paybill number (e.g., 123456)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "mpesa_account_name",
                    models.CharField(
                        blank=True,
                        help_text="M-Pesa account name / reference (what customer enters as reference)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "mpesa_phone",
                    models.CharField(
                        blank=True,
                        help_text="M-Pesa till number or phone (optional, for alternative payment method)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        choices=[
                            ("America/New_York", "America/New_York"),
                            ("America/Chicago", "America/Chicago"),
                            ("America/Los_Angeles", "America/Los_Angeles"),
                            ("America/Denver", "America/Denver"),
                            ("America/Anchorage", "America/Anchorage"),
                            ("America/Toronto", "America/Toronto"),
                            ("America/Mexico_City", "America/Mexico_City"),
                            ("America/Sao_Paulo", "America/Sao_Paulo"),
                            ("America/Buenos_Aires", "America/Buenos_Aires"),
                            ("Europe/London", "Europe/London"),
                            ("Europe/Paris", "Europe/Paris"),
                            ("Europe/Berlin", "Europe/Berlin"),
                            ("Europe/Amsterdam", "Europe/Amsterdam"),
                            ("Europe/Rome", "Europe/Rome"),
                            ("Europe/Stockholm", "Europe/Stockholm"),
                            ("Europe/Moscow", "Europe/Moscow"),
                            ("Africa/Cairo", "Africa/Cairo"),
                            ("Africa/Johannesburg", "Africa/Johannesburg"),
                            ("Africa/Lagos", "Africa/Lagos"),
                            ("Africa/Nairobi", "Africa/Nairobi"),
                            ("Asia/Dubai", "Asia/Dubai"),
                            ("Asia/Kolkata", "Asia/Kolkata"),
                            ("Asia/Bangkok", "Asia/Bangkok"),
                            ("Asia/Hong_Kong", "Asia/Hong_Kong"),
                            ("Asia/Tokyo", "Asia/Tokyo"),
                            ("Asia/Seoul", "Asia/Seoul"),
                            ("Australia/Sydney", "Australia/Sydney"),
                            ("Australia/Melbourne", "Australia/Melbourne"),
                            ("Pacific/Auckland", "Pacific/Auckland"),
                            ("UTC", "UTC"),
                        ],
                        default="Africa/Nairobi",
                        help_text="System timezone for date/time operations",
                        max_length=50,
                    ),
                ),
                (
                    "date_format",
                    models.CharField(
                        choices=[
                            ("MM/DD/YYYY", "MM/DD/YYYY (12-31-2026)"),
                            ("DD/MM/YYYY", "DD/MM/YYYY (31-12-2026)"),
                            ("YYYY-MM-DD", "YYYY-MM-DD (2026-12-31)"),
                        ],
                        default="DD/MM/YYYY",
                        help_text="Display format for dates throughout the system",
                        max_length=20,
                    ),
                ),
                (
                    "currency_symbol",
                    models.CharField(
                        default="KES",
                        help_text="Default currency symbol or code to display",
                        max_length=10,
                    ),
                ),
                (
                    "default_currency",
                    models.CharField(
                        choices=[
                            ("KES", "Kenyan Shilling (KES)"),
                            ("USD", "US Dollar (USD)"),
                            ("EUR", "Euro (EUR)"),
                            ("GBP", "British Pound (GBP)"),
                            ("JPY", "Japanese Yen (JPY)"),
                            ("AUD", "Australian Dollar (AUD)"),
                            ("CAD", "Canadian Dollar (CAD)"),
                            ("CHF", "Swiss Franc (CHF)"),
                            ("CNY", "Chinese Yuan (CNY)"),
                            ("INR", "Indian Rupee (INR)"),
                            ("ZAR", "South African Rand (ZAR)"),
                            ("NGN", "Nigerian Naira (NGN)"),
                        ],
                        default="KES",
                        help_text="Default currency code for all transactions",
                        max_length=3,
                    ),
                ),
                (
                    "decimal_places",
                    models.CharField(
                        choices=[
                            ("2", "2 decimal places (1,234.56)"),
                            ("3", "3 decimal places (1,234.567)"),
                            ("4", "4 decimal places (1,234.5678)"),
                        ],
                        default="2",
                        help_text="Number of decimal places for currency display",
                        max_length=1,
                    ),
                ),
                (
                    "terms_and_conditions",
                    models.TextField(
                        blank=True,
                        default="1. Payment Terms: Net 14 days from invoice date\n2. Prices in KES exclude VAT unless otherwise stated\n3. Goods/services are provided as specified in invoice\n4. Disputes must be raised within 7 days of invoice\n5. All work is subject to our standard terms of engagement\n6. Late payment charges may apply as per Kenyan law\n7. This invoice is valid for payment within 30 days",
                        help_text="Default terms and conditions to display on quotations and invoices",
                        null=True,
                    ),
                ),
                (
                    "enable_payments",
                    models.BooleanField(
                        default=True,
                        help_text="Enable payment tracking and recording features",
                    ),
                ),
                (
                    "enable_reminders",
                    models.BooleanField(
                        default=True,
                        help_text="Enable automatic payment reminders for unpaid invoices",
                    ),
                ),
                (
                    "enable_export",
                    models.BooleanField(
                        default=True,
                        help_text="Enable export features (PDF, Excel, Reports)",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Company Settings",
                "db_table": "core_company_settings",
            },
        ),
        migrations.CreateModel(
            name="EmailConfiguration",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "smtp_host",
                    models.CharField(
                        default="smtp.gmail.com",
                        help_text="SMTP server hostname (e.g., smtp.gmail.com, smtp.office365.com)",
                        max_length=255,
                    ),
                ),
                (
                    "smtp_port",
                    models.IntegerField(
                        default=587,
                        help_text="SMTP port number (typically 587 for TLS, 465 for SSL)",
                    ),
                ),
                (
                    "smtp_username",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SMTP authentication username (usually email address)",
                        max_length=255,
                    ),
                ),
                (
                    "smtp_password_encrypted",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Encrypted SMTP password (write-only)",
                    ),
                ),
                (
                    "smtp_use_tls",
                    models.BooleanField(
                        default=True, help_text="Use STARTTLS for SMTP connection"
                    ),
                ),
                (
                    "smtp_use_ssl",
                    models.BooleanField(
                        default=False,
                        help_text="Use SSL for SMTP connection (typically port 465)",
                    ),
                ),
                (
                    "from_email",
                    models.EmailField(
                        default="no-reply@yourcompany.com",
                        help_text="Email address to send from (verify this is authorized in your SMTP provider)",
                        max_length=254,
                    ),
                ),
                (
                    "from_name",
                    models.CharField(
                        default="Invoice System",
                        help_text="Sender display name in email clients",
                        max_length=255,
                    ),
                ),
                (
                    "enable_invoice_created",
                    models.BooleanField(
                        default=True, help_text="Send email when invoice is created"
                    ),
                ),
                (
                    "enable_invoice_sent",
                    models.BooleanField(
                        default=True,
                        help_text="Send email when invoice is marked as sent",
                    ),
                ),
                (
                    "enable_payment_received",
                    models.BooleanField(
                        default=True, help_text="Send email when payment is received"
                    ),
                ),
                (
                    "enable_payment_overdue",
                    models.BooleanField(
                        default=True,
                        help_text="Send email for overdue payment reminders",
                    ),
                ),
                (
                    "send_to_client_on_creation",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically send invoice to client when created",
                    ),
                ),
                (
                    "days_before_due_reminder",
                    models.IntegerField(
                        default=3,
                        help_text="Days before invoice is due to send reminder email",
                    ),
                ),
                (
                    "is_configured",
                    models.BooleanField(
                        default=False,
                        help_text="Whether email configuration has been properly tested and is ready to use",
                    ),
                ),
                (
                    "last_tested_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When SMTP connection was last tested",
                        null=True,
                    ),
                ),
                (
                    "last_test_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Test"),
                            ("success", "Test Successful"),
                            ("failed", "Test Failed"),
                            ("error", "Configuration Error"),
                        ],
                        default="pending",
                        help_text="Result of last SMTP test",
                        max_length=50,
                    ),
                ),
                (
                    "last_test_error",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error message from last failed test (for debugging)",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Email Configuration",
                "db_table": "core_email_configuration",
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.CharField(
                        db_index=True,
                        default=invoicing_app.core.models.generate_uuid,
                        editable=False,
                        help_text="External API reference (UUID4)",
                        max_length=36,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Soft delete flag"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("invoicing", "Invoicing & Quotations"),
                            ("payments", "Payments"),
                            ("clients", "Client Management"),
                            ("products", "Products & Services"),
                            ("reports", "Reports & Analysis"),
                            ("settings", "Settings & Configuration"),
                            ("technical", "Technical Issues"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        help_text="FAQ category",
                        max_length=20,
                    ),
                ),
                (
                    "question",
                    models.CharField(
                        help_text="The frequently asked question", max_length=500
                    ),
                ),
                (
                    "answer",
                    models.TextField(help_text="Detailed answer to the question"),
                ),
                (
                    "order",
                    models.SmallIntegerField(
                        default=0, help_text="Display order within category"
                    ),
                ),
                (
                    "views_count",
                    models.IntegerField(
                        default=0, help_text="Number of times this FAQ has been viewed"
                    ),
                ),
                (
                    "helpful_yes",
                    models.IntegerField(
                        default=0, help_text="Number of 'helpful' votes"
                    ),
                ),
                (
                    "helpful_no",
                    models.IntegerField(
                        default=0, help_text="Number of 'not helpful' votes"
                    ),
                ),
            ],
            options={
                "db_table": "core_faq",
                "ordering": ["category", "order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["category", "order"], name="core_faq_categor_468fef_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="core_faq_is_acti_90717d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HelpArticle",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.CharField(
                        db_index=True,
                        default=invoicing_app.core.models.generate_uuid,
                        editable=False,
                        help_text="External API reference (UUID4)",
                        max_length=36,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Soft delete flag"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, help_text="Article title", max_length=300
                    ),
                ),
                (
                    "slug",
                    models.SlugField(help_text="URL-friendly identifier", unique=True),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("getting-started", "Getting Started"),
                            ("invoicing", "Invoicing & Quotations"),
                            ("payments", "Payments"),
                            ("clients", "Client Management"),
                            ("products", "Products & Services"),
                            ("reports", "Reports & Analysis"),
                            ("settings", "Settings & Configuration"),
                            ("integration", "Integrations"),
                            ("api", "API Documentation"),
                            ("troubleshooting", "Troubleshooting"),
                        ],
                        db_index=True,
                        help_text="Help article category",
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Full article content (supports HTML/Markdown)"
                    ),
                ),
                (
                    "excerpt",
                    models.CharField(
                        blank=True,
                        help_text="Short preview of article content",
                        max_length=500,
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        default="Admin", help_text="Article author", max_length=100
                    ),
                ),
                (
                    "views_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of times this article has been viewed",
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Featured article on help homepage",
                    ),
                ),
                (
                    "order",
                    models.SmallIntegerField(
                        default=0, help_text="Display order within category"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated tags for search",
                        max_length=500,
                    ),
                ),
            ],
            options={
                "db_table": "core_help_article",
                "ordering": ["-featured", "category", "order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["category", "order"],
                        name="core_help_a_categor_bcada8_idx",
                    ),
                    models.Index(
                        fields=["featured", "-created_at"],
                        name="core_help_a_feature_97c94d_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="core_help_a_is_acti_473bf0_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.CharField(
                        db_index=True,
                        default=invoicing_app.core.models.generate_uuid,
                        editable=False,
                        help_text="External API reference (UUID4)",
                        max_length=36,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Soft delete flag"
                    ),
                ),
                (
                    "ticket_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique ticket identifier",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Submitter's name", max_length=200),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Submitter's email address",
                        max_length=254,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Support ticket subject", max_length=300
                    ),
                ),
                (
                    "message",
                    models.TextField(help_text="Detailed support request message"),
                ),
                (
                    "category",
                    models.CharField(
                        default="general",
                        help_text="Support ticket category",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        help_text="Ticket priority level",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="open",
                        help_text="Current ticket status",
                        max_length=15,
                    ),
                ),
                (
                    "assigned_to",
                    models.CharField(
                        blank=True,
                        help_text="Team member assigned to ticket",
                        max_length=100,
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes and resolution details"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, help_text="When the ticket was resolved", null=True
                    ),
                ),
                (
                    "attachment_url",
                    models.URLField(blank=True, help_text="URL to any attachment"),
                ),
            ],
            options={
                "db_table": "core_support_ticket",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="core_suppor_status_d6433e_idx",
                    ),
                    models.Index(
                        fields=["priority", "status"],
                        name="core_suppor_priorit_d40aa1_idx",
                    ),
                    models.Index(fields=["email"], name="core_suppor_email_dd5e33_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Backup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        db_index=True,
                        help_text="Name of backup file",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="Full path to backup file on disk", max_length=500
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(help_text="Size of backup in bytes"),
                ),
                (
                    "backup_type",
                    models.CharField(
                        choices=[
                            ("database", "Database"),
                            ("full", "Full System"),
                            ("incremental", "Incremental"),
                        ],
                        default="database",
                        help_text="Type of backup",
                        max_length=20,
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="How long backup took to complete",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                            ("verified", "Verified"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current backup status",
                        max_length=20,
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True,
                        help_text="SHA256 checksum for integrity verification",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "is_compressed",
                    models.BooleanField(
                        default=False, help_text="Whether backup is compressed"
                    ),
                ),
                (
                    "is_automated",
                    models.BooleanField(
                        default=False,
                        help_text="Was this backup created automatically?",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional backup notes", null=True
                    ),
                ),
                (
                    "restored_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this backup was last restored",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who initiated backup",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backup_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restored_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who restored from this backup",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backup_restored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_backup",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="core_backup_status_beb151_idx",
                    ),
                    models.Index(
                        fields=["backup_type", "-created_at"],
                        name="core_backup_backup__a84af1_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SavedFilter",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of this filter preset (e.g., 'Unpaid Invoices Over 30 Days')",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this filter shows",
                        null=True,
                    ),
                ),
                (
                    "filter_type",
                    models.CharField(
                        choices=[
                            ("invoice", "Invoices"),
                            ("payment", "Payments"),
                            ("client", "Clients"),
                            ("quotation", "Quotations"),
                            ("expense", "Expenses"),
                        ],
                        db_index=True,
                        help_text="What entity type this filter applies to",
                        max_length=50,
                    ),
                ),
                (
                    "filter_criteria",
                    models.JSONField(
                        default=dict,
                        help_text="Filter conditions as JSON (e.g., {'status': 'unpaid', 'days_overdue': {'gte': 30}})",
                    ),
                ),
                (
                    "is_global",
                    models.BooleanField(
                        default=False,
                        help_text="If True, visible to all users; if False, only visible to creator",
                    ),
                ),
                (
                    "sort_by",
                    models.CharField(
                        blank=True,
                        help_text="Field to sort by (e.g., 'invoice_date', '-amount')",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "last_used",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this filter was applied",
                        null=True,
                    ),
                ),
                (
                    "use_count",
                    models.IntegerField(
                        default=0, help_text="Number of times this filter has been used"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this filter",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_filters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_savedfilter",
                "ordering": ["-last_used", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_by", "filter_type"],
                        name="core_savedf_created_331493_idx",
                    ),
                    models.Index(
                        fields=["filter_type", "is_global"],
                        name="core_savedf_filter__5e15f1_idx",
                    ),
                    models.Index(
                        fields=["-last_used"], name="core_savedf_last_us_c9c769_idx"
                    ),
                ],
            },
        ),
    ]
