# Generated by Django 4.2.28 on 2026-02-15 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('file_name', models.CharField(db_index=True, help_text='Name of backup file', max_length=255, unique=True)),
                ('file_path', models.CharField(help_text='Full path to backup file on disk', max_length=500)),
                ('file_size', models.BigIntegerField(help_text='Size of backup in bytes')),
                ('backup_type', models.CharField(choices=[('database', 'Database'), ('full', 'Full System'), ('incremental', 'Incremental')], default='database', help_text='Type of backup', max_length=20)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='How long backup took to complete', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('failed', 'Failed'), ('verified', 'Verified')], db_index=True, default='pending', help_text='Current backup status', max_length=20)),
                ('checksum', models.CharField(blank=True, help_text='SHA256 checksum for integrity verification', max_length=64, null=True)),
                ('is_compressed', models.BooleanField(default=False, help_text='Whether backup is compressed')),
                ('is_automated', models.BooleanField(default=False, help_text='Was this backup created automatically?')),
                ('notes', models.TextField(blank=True, help_text='Additional backup notes', null=True)),
                ('restored_at', models.DateTimeField(blank=True, help_text='When this backup was last restored', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who initiated backup', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_created', to=settings.AUTH_USER_MODEL)),
                ('restored_by', models.ForeignKey(blank=True, help_text='User who restored from this backup', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_restored', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_backup',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='core_backup_status_beb151_idx'), models.Index(fields=['backup_type', '-created_at'], name='core_backup_backup__a84af1_idx')],
            },
        ),
    ]
