# Generated by Django 4.2.28 on 2026-02-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(default='Your Company Name', help_text='Official company name', max_length=255)),
                ('company_website', models.URLField(blank=True, help_text='Company website URL', null=True)),
                ('company_logo', models.ImageField(blank=True, help_text='Company logo image (PNG/JPG, max 2MB, recommended 300x150px)', null=True, upload_to='company/')),
                ('company_email', models.EmailField(default='info@yourcompany.com', help_text='Primary contact email address', max_length=254)),
                ('company_phone', models.CharField(default='+1-234-567-8900', help_text='Primary phone number', max_length=20)),
                ('company_address', models.TextField(default='123 Business St, City, Country', help_text='Full company address')),
                ('tax_id', models.CharField(blank=True, help_text='Tax ID / VAT Registration Number (e.g., KRA PIN for Kenya)', max_length=50, null=True)),
                ('invoice_prefix', models.CharField(default='INV', help_text='Prefix for invoice numbers (e.g., INV-2026-0001)', max_length=10)),
                ('financial_year_start', models.IntegerField(default=1, help_text='Month number when financial year starts (1-12)')),
                ('footer_message', models.TextField(blank=True, help_text='Custom message to display in invoice footer', null=True)),
                ('default_payment_terms', models.CharField(blank=True, help_text='Default payment terms for invoices (e.g., Net 30 days)', max_length=200, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Company Settings',
                'db_table': 'core_company_settings',
            },
        ),
    ]
