# Generated by Django 4.2.28 on 2026-02-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_company_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='currency_symbol',
            field=models.CharField(default='$', help_text='Default currency symbol or code to display', max_length=10),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='date_format',
            field=models.CharField(choices=[('MM/DD/YYYY', 'MM/DD/YYYY (12-31-2026)'), ('DD/MM/YYYY', 'DD/MM/YYYY (31-12-2026)'), ('YYYY-MM-DD', 'YYYY-MM-DD (2026-12-31)')], default='MM/DD/YYYY', help_text='Display format for dates throughout the system', max_length=20),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='decimal_places',
            field=models.CharField(choices=[('2', '2 decimal places (1,234.56)'), ('3', '3 decimal places (1,234.567)'), ('4', '4 decimal places (1,234.5678)')], default='2', help_text='Number of decimal places for currency display', max_length=1),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='timezone',
            field=models.CharField(choices=[('America/New_York', 'America/New_York'), ('America/Chicago', 'America/Chicago'), ('America/Los_Angeles', 'America/Los_Angeles'), ('America/Denver', 'America/Denver'), ('America/Anchorage', 'America/Anchorage'), ('America/Toronto', 'America/Toronto'), ('America/Mexico_City', 'America/Mexico_City'), ('America/Sao_Paulo', 'America/Sao_Paulo'), ('America/Buenos_Aires', 'America/Buenos_Aires'), ('Europe/London', 'Europe/London'), ('Europe/Paris', 'Europe/Paris'), ('Europe/Berlin', 'Europe/Berlin'), ('Europe/Amsterdam', 'Europe/Amsterdam'), ('Europe/Rome', 'Europe/Rome'), ('Europe/Stockholm', 'Europe/Stockholm'), ('Europe/Moscow', 'Europe/Moscow'), ('Africa/Cairo', 'Africa/Cairo'), ('Africa/Johannesburg', 'Africa/Johannesburg'), ('Africa/Lagos', 'Africa/Lagos'), ('Africa/Nairobi', 'Africa/Nairobi'), ('Asia/Dubai', 'Asia/Dubai'), ('Asia/Kolkata', 'Asia/Kolkata'), ('Asia/Bangkok', 'Asia/Bangkok'), ('Asia/Hong_Kong', 'Asia/Hong_Kong'), ('Asia/Tokyo', 'Asia/Tokyo'), ('Asia/Seoul', 'Asia/Seoul'), ('Australia/Sydney', 'Australia/Sydney'), ('Australia/Melbourne', 'Australia/Melbourne'), ('Pacific/Auckland', 'Pacific/Auckland'), ('UTC', 'UTC')], default='UTC', help_text='System timezone for date/time operations', max_length=50),
        ),
    ]
