# Generated by Django 4.2.28 on 2026-02-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_companysettings_currency_symbol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='payment_prefix',
            field=models.CharField(default='REC', help_text='Prefix for payment receipt numbers (e.g., REC-2026-0001)', max_length=10),
        ),
    ]
