# Generated by Django 4.2.28 on 2026-02-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_companysettings_payment_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='enable_export',
            field=models.BooleanField(default=True, help_text='Enable export features (PDF, Excel, Reports)'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='enable_payments',
            field=models.BooleanField(default=True, help_text='Enable payment tracking and recording features'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='enable_reminders',
            field=models.BooleanField(default=True, help_text='Enable automatic payment reminders for unpaid invoices'),
        ),
    ]
