# Generated by Django 4.2.28 on 2026-02-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_companysettings_enable_export_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='bank_account_name',
            field=models.CharField(blank=True, help_text='Bank account holder name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='Bank account number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='bank_branch',
            field=models.CharField(blank=True, help_text='Bank branch (optional)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='bank_iban',
            field=models.CharField(blank=True, help_text='IBAN (optional, for international transfers)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='bank_swift_code',
            field=models.CharField(blank=True, help_text='SWIFT code (optional, for international transfers)', max_length=50, null=True),
        ),
    ]
