# Generated by Django 4.2.28 on 2026-02-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_companysettings_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='mpesa_account_name',
            field=models.CharField(blank=True, help_text='M-Pesa account name / reference (what customer enters as reference)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='mpesa_paybill_number',
            field=models.CharField(blank=True, help_text='M-Pesa Paybill number (e.g., 123456)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='mpesa_phone',
            field=models.CharField(blank=True, help_text='M-Pesa till number or phone (optional, for alternative payment method)', max_length=20, null=True),
        ),
    ]
