# Generated by Django 4.2.28 on 2026-02-21 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_companysettings_mpesa_account_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companysettings",
            name="footer_message",
        ),
    ]
