# Generated by Django 4.2.28 on 2026-02-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_companysettings_footer_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('smtp_host', models.CharField(default='smtp.gmail.com', help_text='SMTP server hostname (e.g., smtp.gmail.com, smtp.office365.com)', max_length=255)),
                ('smtp_port', models.IntegerField(default=587, help_text='SMTP port number (typically 587 for TLS, 465 for SSL)')),
                ('smtp_username', models.CharField(blank=True, default='', help_text='SMTP authentication username (usually email address)', max_length=255)),
                ('smtp_password_encrypted', models.TextField(blank=True, default='', help_text='Encrypted SMTP password (write-only)')),
                ('smtp_use_tls', models.BooleanField(default=True, help_text='Use STARTTLS for SMTP connection')),
                ('smtp_use_ssl', models.BooleanField(default=False, help_text='Use SSL for SMTP connection (typically port 465)')),
                ('from_email', models.EmailField(default='no-reply@yourcompany.com', help_text='Email address to send from (verify this is authorized in your SMTP provider)', max_length=254)),
                ('from_name', models.CharField(default='Invoice System', help_text='Sender display name in email clients', max_length=255)),
                ('enable_invoice_created', models.BooleanField(default=True, help_text='Send email when invoice is created')),
                ('enable_invoice_sent', models.BooleanField(default=True, help_text='Send email when invoice is marked as sent')),
                ('enable_payment_received', models.BooleanField(default=True, help_text='Send email when payment is received')),
                ('enable_payment_overdue', models.BooleanField(default=True, help_text='Send email for overdue payment reminders')),
                ('send_to_client_on_creation', models.BooleanField(default=False, help_text='Automatically send invoice to client when created')),
                ('days_before_due_reminder', models.IntegerField(default=3, help_text='Days before invoice is due to send reminder email')),
                ('is_configured', models.BooleanField(default=False, help_text='Whether email configuration has been properly tested and is ready to use')),
                ('last_tested_at', models.DateTimeField(blank=True, help_text='When SMTP connection was last tested', null=True)),
                ('last_test_status', models.CharField(choices=[('pending', 'Pending Test'), ('success', 'Test Successful'), ('failed', 'Test Failed'), ('error', 'Configuration Error')], default='pending', help_text='Result of last SMTP test', max_length=50)),
                ('last_test_error', models.TextField(blank=True, default='', help_text='Error message from last failed test (for debugging)')),
            ],
            options={
                'verbose_name_plural': 'Email Configuration',
                'db_table': 'core_email_configuration',
            },
        ),
    ]
