# Generated by Django 4.2.28 on 2026-02-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_emailconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='quote_prefix',
            field=models.CharField(default='QUOTE', help_text='Prefix for quotation numbers (e.g., QUOTE-2026-0001)', max_length=10),
        ),
    ]
