# Generated by Django 4.2.28 on 2026-02-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_companysettings_quote_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='terms_and_conditions',
            field=models.TextField(blank=True, help_text='Default terms and conditions to display on quotations and invoices', null=True),
        ),
    ]
