# Generated by Django 4.2.28 on 2026-02-23 16:52

from django.db import migrations, models
import invoicing_app.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_companysettings_terms_and_conditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_index=True, default=invoicing_app.core.models.generate_uuid, editable=False, help_text='External API reference (UUID4)', max_length=36, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('ticket_number', models.CharField(db_index=True, help_text='Unique ticket identifier', max_length=20, unique=True)),
                ('name', models.CharField(help_text="Submitter's name", max_length=200)),
                ('email', models.EmailField(db_index=True, help_text="Submitter's email address", max_length=254)),
                ('subject', models.CharField(help_text='Support ticket subject', max_length=300)),
                ('message', models.TextField(help_text='Detailed support request message')),
                ('category', models.CharField(default='general', help_text='Support ticket category', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Ticket priority level', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', help_text='Current ticket status', max_length=15)),
                ('assigned_to', models.CharField(blank=True, help_text='Team member assigned to ticket', max_length=100)),
                ('resolution_notes', models.TextField(blank=True, help_text='Internal notes and resolution details')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the ticket was resolved', null=True)),
                ('attachment_url', models.URLField(blank=True, help_text='URL to any attachment')),
            ],
            options={
                'db_table': 'core_support_ticket',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='core_suppor_status_d6433e_idx'), models.Index(fields=['priority', 'status'], name='core_suppor_priorit_d40aa1_idx'), models.Index(fields=['email'], name='core_suppor_email_dd5e33_idx')],
            },
        ),
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_index=True, default=invoicing_app.core.models.generate_uuid, editable=False, help_text='External API reference (UUID4)', max_length=36, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('title', models.CharField(db_index=True, help_text='Article title', max_length=300)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', unique=True)),
                ('category', models.CharField(choices=[('getting-started', 'Getting Started'), ('invoicing', 'Invoicing & Quotations'), ('payments', 'Payments'), ('clients', 'Client Management'), ('products', 'Products & Services'), ('reports', 'Reports & Analysis'), ('settings', 'Settings & Configuration'), ('integration', 'Integrations'), ('api', 'API Documentation'), ('troubleshooting', 'Troubleshooting')], db_index=True, help_text='Help article category', max_length=20)),
                ('content', models.TextField(help_text='Full article content (supports HTML/Markdown)')),
                ('excerpt', models.CharField(blank=True, help_text='Short preview of article content', max_length=500)),
                ('author', models.CharField(default='Admin', help_text='Article author', max_length=100)),
                ('views_count', models.IntegerField(default=0, help_text='Number of times this article has been viewed')),
                ('featured', models.BooleanField(db_index=True, default=False, help_text='Featured article on help homepage')),
                ('order', models.SmallIntegerField(default=0, help_text='Display order within category')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for search', max_length=500)),
            ],
            options={
                'db_table': 'core_help_article',
                'ordering': ['-featured', 'category', 'order', '-created_at'],
                'indexes': [models.Index(fields=['category', 'order'], name='core_help_a_categor_bcada8_idx'), models.Index(fields=['featured', '-created_at'], name='core_help_a_feature_97c94d_idx'), models.Index(fields=['is_active'], name='core_help_a_is_acti_473bf0_idx')],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_index=True, default=invoicing_app.core.models.generate_uuid, editable=False, help_text='External API reference (UUID4)', max_length=36, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('category', models.CharField(choices=[('invoicing', 'Invoicing & Quotations'), ('payments', 'Payments'), ('clients', 'Client Management'), ('products', 'Products & Services'), ('reports', 'Reports & Analysis'), ('settings', 'Settings & Configuration'), ('technical', 'Technical Issues'), ('other', 'Other')], db_index=True, help_text='FAQ category', max_length=20)),
                ('question', models.CharField(help_text='The frequently asked question', max_length=500)),
                ('answer', models.TextField(help_text='Detailed answer to the question')),
                ('order', models.SmallIntegerField(default=0, help_text='Display order within category')),
                ('views_count', models.IntegerField(default=0, help_text='Number of times this FAQ has been viewed')),
                ('helpful_yes', models.IntegerField(default=0, help_text="Number of 'helpful' votes")),
                ('helpful_no', models.IntegerField(default=0, help_text="Number of 'not helpful' votes")),
            ],
            options={
                'db_table': 'core_faq',
                'ordering': ['category', 'order', '-created_at'],
                'indexes': [models.Index(fields=['category', 'order'], name='core_faq_categor_468fef_idx'), models.Index(fields=['is_active'], name='core_faq_is_acti_90717d_idx')],
            },
        ),
    ]
