# Generated by Django 4.2.28 on 2026-02-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_help_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='default_currency',
            field=models.CharField(choices=[('KES', 'Kenyan Shilling (KES)'), ('USD', 'US Dollar (USD)')], default='KES', help_text='Default currency code for all transactions', max_length=3),
        ),
    ]
