# Generated by Django 4.2.28 on 2026-02-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_default_currency_to_companysettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='default_currency',
            field=models.CharField(choices=[('KES', 'Kenyan Shilling (KES)'), ('USD', 'US Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('GBP', 'British Pound (GBP)'), ('JPY', 'Japanese Yen (JPY)'), ('AUD', 'Australian Dollar (AUD)'), ('CAD', 'Canadian Dollar (CAD)'), ('CHF', 'Swiss Franc (CHF)'), ('CNY', 'Chinese Yuan (CNY)'), ('INR', 'Indian Rupee (INR)'), ('ZAR', 'South African Rand (ZAR)'), ('NGN', 'Nigerian Naira (NGN)')], default='KES', help_text='Default currency code for all transactions', max_length=3),
        ),
    ]
