# Generated by Django 4.2.28 on 2026-02-27 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_alter_companysettings_default_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Name of this filter preset (e.g., 'Unpaid Invoices Over 30 Days')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of what this filter shows', null=True)),
                ('filter_type', models.CharField(choices=[('invoice', 'Invoices'), ('payment', 'Payments'), ('client', 'Clients'), ('quotation', 'Quotations'), ('expense', 'Expenses')], db_index=True, help_text='What entity type this filter applies to', max_length=50)),
                ('filter_criteria', models.JSONField(default=dict, help_text="Filter conditions as JSON (e.g., {'status': 'unpaid', 'days_overdue': {'gte': 30}})")),
                ('is_global', models.BooleanField(default=False, help_text='If True, visible to all users; if False, only visible to creator')),
                ('sort_by', models.CharField(blank=True, help_text="Field to sort by (e.g., 'invoice_date', '-amount')", max_length=100, null=True)),
                ('last_used', models.DateTimeField(blank=True, help_text='Last time this filter was applied', null=True)),
                ('use_count', models.IntegerField(default=0, help_text='Number of times this filter has been used')),
                ('created_by', models.ForeignKey(help_text='User who created this filter', on_delete=django.db.models.deletion.CASCADE, related_name='saved_filters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_savedfilter',
                'ordering': ['-last_used', '-created_at'],
                'indexes': [models.Index(fields=['created_by', 'filter_type'], name='core_savedf_created_331493_idx'), models.Index(fields=['filter_type', 'is_global'], name='core_savedf_filter__5e15f1_idx'), models.Index(fields=['-last_used'], name='core_savedf_last_us_c9c769_idx')],
            },
        ),
    ]
