# Generated by Django 5.1 on 2026-04-03 12:54

import django.db.models.deletion
import django.utils.timezone
import invoicing_app.core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("invoices", "0001_initial"),
        ("products", "0001_initial"),
        ("taxes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.CharField(
                        db_index=True,
                        default=invoicing_app.core.models.generate_uuid,
                        editable=False,
                        help_text="External API reference (UUID4)",
                        max_length=36,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Soft delete flag"
                    ),
                ),
                (
                    "quote_number",
                    models.CharField(
                        db_index=True,
                        help_text="Quote number (e.g., QUOTE-2026-0001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "quote_date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Date quote was prepared",
                    ),
                ),
                ("valid_until", models.DateField(help_text="Quote expiration date")),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Quote description/terms", null=True
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("KES", "Kenyan Shilling"), ("USD", "US Dollar")],
                        default="KES",
                        help_text="Quote currency",
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("issued", "Issued"),
                            ("sent", "Sent to Client"),
                            ("viewed", "Viewed by Client"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                            ("converted", "Converted to Invoice"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Quote status",
                        max_length=20,
                    ),
                ),
                (
                    "subtotal_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Sum of line item amounts (excl. VAT)",
                        max_digits=15,
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total VAT",
                        max_digits=15,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Subtotal + VAT",
                        max_digits=15,
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When quote was formally issued",
                        null=True,
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, help_text="When quote was sent to client", null=True
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(
                        blank=True, help_text="When client viewed quote", null=True
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, help_text="When quote was accepted", null=True
                    ),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(
                        blank=True, help_text="When quote was rejected", null=True
                    ),
                ),
                (
                    "expired_at",
                    models.DateTimeField(
                        blank=True, help_text="When quote expired", null=True
                    ),
                ),
                (
                    "converted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When quote was converted to invoice",
                        null=True,
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, help_text="Reason for rejection", null=True
                    ),
                ),
                (
                    "quote_pdf",
                    models.FileField(
                        blank=True,
                        help_text="Cached PDF file path",
                        null=True,
                        upload_to="quotes/pdfs/",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Client this quote is for",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotes",
                        to="clients.client",
                    ),
                ),
                (
                    "converted_invoice",
                    models.OneToOneField(
                        blank=True,
                        help_text="Invoice created from this quote",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_quote",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this quote",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_quotes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this quote",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_quotes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "quotations_quote",
                "ordering": ["-quote_date", "-quote_number"],
            },
        ),
        migrations.CreateModel(
            name="QuoteLineItem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "description",
                    models.CharField(
                        help_text="Description (mandatory if product is NULL)",
                        max_length=500,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, help_text="Quantity", max_digits=12
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per unit (excl. VAT)",
                        max_digits=15,
                    ),
                ),
                (
                    "line_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="quantity × unit_price (excl. VAT)",
                        max_digits=15,
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Calculated VAT (line_amount × tax_rate%)",
                        max_digits=15,
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="line_amount + tax_amount (incl. VAT)",
                        max_digits=15,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Line-item-specific notes", null=True
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(default=0, help_text="Display order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Product (optional; if NULL, manual line item)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quote_lines",
                        to="products.product",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        help_text="Quote this line item belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="quotations.quote",
                    ),
                ),
                (
                    "tax_rate",
                    models.ForeignKey(
                        help_text="Which tax rate applies to this line",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quote_line_items",
                        to="taxes.taxrate",
                    ),
                ),
            ],
            options={
                "db_table": "quotations_quotelineitem",
                "ordering": ["quote", "sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuoteNumberSequence",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "prefix",
                    models.CharField(
                        default="QUOTE",
                        help_text="Quote number prefix (QUOTE, PROPOSAL, etc.)",
                        max_length=20,
                    ),
                ),
                ("year", models.IntegerField(help_text="Calendar year")),
                (
                    "next_sequence",
                    models.BigIntegerField(
                        default=1, help_text="Next sequence number to use"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "quotations_quotenumbersequence",
                "indexes": [
                    models.Index(
                        fields=["prefix", "year"], name="quotations__prefix_6c1f60_idx"
                    )
                ],
                "unique_together": {("prefix", "year")},
            },
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(
                fields=["quote_number"], name="quotations__quote_n_a8d63e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(
                fields=["client"], name="quotations__client__3b7bc3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(fields=["status"], name="quotations__status_17b6cf_idx"),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(
                fields=["quote_date"], name="quotations__quote_d_36446d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(
                fields=["valid_until"], name="quotations__valid_u_94f643_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(
                fields=["status", "valid_until"], name="quotations__status_106a63_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quotelineitem",
            index=models.Index(fields=["quote"], name="quotations__quote_i_756ee2_idx"),
        ),
        migrations.AddIndex(
            model_name="quotelineitem",
            index=models.Index(
                fields=["product"], name="quotations__product_2193ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quotelineitem",
            index=models.Index(
                fields=["tax_rate"], name="quotations__tax_rat_c7a360_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quotelineitem",
            index=models.Index(
                fields=["quote", "product"], name="quotations__quote_i_c9f2e6_idx"
            ),
        ),
    ]
