# Generated by Django 4.2.28 on 2026-02-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="issued_at",
            field=models.DateTimeField(
                blank=True, help_text="When quote was formally issued", null=True
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("issued", "Issued"),
                    ("sent", "Sent to Client"),
                    ("viewed", "Viewed by Client"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                    ("converted", "Converted to Invoice"),
                    ("archived", "Archived"),
                ],
                db_index=True,
                default="draft",
                help_text="Quote status",
                max_length=20,
            ),
        ),
    ]
