# Generated by Django 5.1 on 2026-04-03 12:54

import django.db.models.deletion
import invoicing_app.core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name (e.g., Office Supplies, Travel, Utilities)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Category description", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this category active?"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Expense Categories",
                "db_table": "expenses_category",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Vendor name", max_length=255, unique=True
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Vendor contact email",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="Vendor phone number",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, help_text="Vendor address", null=True),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        blank=True,
                        help_text="Payment terms (e.g., Net 30, Net 60)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this vendor active?"
                    ),
                ),
            ],
            options={
                "db_table": "expenses_vendor",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseBudget",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "category",
                    models.OneToOneField(
                        help_text="Expense category",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="budget",
                        serialize=False,
                        to="expenses.expensecategory",
                    ),
                ),
                (
                    "monthly_limit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monthly budget limit",
                        max_digits=12,
                    ),
                ),
                (
                    "annual_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual budget limit (optional)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "alert_threshold",
                    models.IntegerField(
                        default=80,
                        help_text="Alert when spending reaches this % of limit",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Expense Budgets",
                "db_table": "expenses_budget",
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.CharField(
                        db_index=True,
                        default=invoicing_app.core.models.generate_uuid,
                        editable=False,
                        help_text="External API reference (UUID4)",
                        max_length=36,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Soft delete flag"
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="What was this expense for?"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Expense amount", max_digits=12
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="KES",
                        help_text="Currency code (e.g., USD, KES)",
                        max_length=3,
                    ),
                ),
                (
                    "expense_date",
                    models.DateField(help_text="When was this expense incurred?"),
                ),
                (
                    "submitted_date",
                    models.DateField(
                        auto_now_add=True,
                        help_text="When was this submitted for approval?",
                        null=True,
                    ),
                ),
                (
                    "approved_date",
                    models.DateField(
                        blank=True, help_text="When was this approved?", null=True
                    ),
                ),
                (
                    "paid_date",
                    models.DateField(
                        blank=True, help_text="When was this paid?", null=True
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank Transfer"),
                            ("credit_card", "Credit Card"),
                            ("check", "Check"),
                            ("mpesa", "M-Pesa"),
                            ("other", "Other"),
                        ],
                        default="bank_transfer",
                        help_text="How was this expense paid?",
                        max_length=20,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="Invoice/receipt number or reference",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("paid", "Paid"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Expense status",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this expense",
                        null=True,
                    ),
                ),
                (
                    "receipt_file",
                    models.FileField(
                        blank=True,
                        help_text="Receipt or invoice document",
                        null=True,
                        upload_to="receipts/%Y/%m/",
                    ),
                ),
                (
                    "is_reimbursable",
                    models.BooleanField(
                        default=False,
                        help_text="Is this expense reimbursable to an employee?",
                    ),
                ),
                (
                    "reimbursed_to",
                    models.CharField(
                        blank=True,
                        help_text="Name of person to reimburse",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "reimbursement_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount reimbursed",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who approved this expense",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who submitted this expense",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Expense category",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="expenses.expensecategory",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which vendor this expense is from",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="expenses.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "expenses_expense",
                "ordering": ["-expense_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["category", "-expense_date"],
                        name="expenses_ex_categor_6321f1_idx",
                    ),
                    models.Index(
                        fields=["status", "-expense_date"],
                        name="expenses_ex_status_e5d781_idx",
                    ),
                    models.Index(
                        fields=["vendor", "-expense_date"],
                        name="expenses_ex_vendor__fd04e6_idx",
                    ),
                ],
            },
        ),
    ]
