# Generated by Django 5.1 on 2026-04-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Template name (invoice_issued, payment_reminder, etc.)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Email subject template", max_length=200
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Email body template (supports Django template syntax)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this template is active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "notifications_emailtemplate",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "entity_type",
                    models.CharField(
                        help_text="Entity type (invoice, payment, etc.)", max_length=50
                    ),
                ),
                ("entity_id", models.BigIntegerField(help_text="ID of entity")),
                (
                    "notification_type",
                    models.CharField(
                        help_text="Type of notification (email_sent, payment_reminder, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "recipient",
                    models.CharField(
                        help_text="Recipient email or phone", max_length=255
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="Email subject or SMS content",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Notification status",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if failed", null=True
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, help_text="When notification was sent", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "notifications_notificationlog",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="notificatio_entity__913abc_idx",
                    ),
                    models.Index(
                        fields=["status"], name="notificatio_status_a242db_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="notificatio_created_01830a_idx"
                    ),
                ],
            },
        ),
    ]
