# Generated by Django 5.1 on 2026-04-03 12:54

import django.core.validators
import django.db.models.deletion
import invoicing_app.core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.CharField(
                        db_index=True,
                        default=invoicing_app.core.models.generate_uuid,
                        editable=False,
                        help_text="External API reference (UUID4)",
                        max_length=36,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Soft delete flag"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Organization/Company name", max_length=255
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier (e.g., 'acme-corp')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Organization description", null=True
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, help_text="Organization's website", null=True
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Organization logo",
                        null=True,
                        upload_to="organization_logos/",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("starter", "Starter"),
                            ("professional", "Professional"),
                            ("enterprise", "Enterprise"),
                        ],
                        db_index=True,
                        default="free",
                        help_text="Current subscription plan",
                        max_length=50,
                    ),
                ),
                (
                    "admin_email",
                    models.EmailField(
                        help_text="Primary admin email for this organization",
                        max_length=254,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Organization contact phone",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "invoice_count",
                    models.IntegerField(
                        default=0,
                        help_text="Total invoices created (for usage tracking)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "user_count",
                    models.IntegerField(
                        default=1,
                        help_text="Number of active users in organization",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "subscription_started",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When organization was created"
                    ),
                ),
                (
                    "subscription_renew_date",
                    models.DateField(
                        blank=True,
                        help_text="When current subscription renews",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended - Payment Issue"),
                            ("cancelled", "Cancelled"),
                            ("trial", "Trial"),
                        ],
                        db_index=True,
                        default="active",
                        help_text="Organization status",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stripe Customer ID for billing",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stripe Subscription ID",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "enable_api_access",
                    models.BooleanField(
                        default=False,
                        help_text="Allow API access for this organization",
                    ),
                ),
                (
                    "enable_custom_branding",
                    models.BooleanField(
                        default=False,
                        help_text="Allow custom company branding (premium feature)",
                    ),
                ),
                (
                    "enable_advanced_analytics",
                    models.BooleanField(
                        default=False,
                        help_text="Enable advanced analytics (premium feature)",
                    ),
                ),
                (
                    "enable_api_webhooks",
                    models.BooleanField(
                        default=False,
                        help_text="Enable webhook notifications (premium feature)",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="API key for external integrations",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
            options={
                "db_table": "organizations_organization",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["slug"], name="organizatio_slug_048085_idx"),
                    models.Index(fields=["plan"], name="organizatio_plan_c562f2_idx"),
                    models.Index(
                        fields=["status"], name="organizatio_status_295901_idx"
                    ),
                    models.Index(
                        fields=["stripe_customer_id"],
                        name="organizatio_stripe__263a52_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.CharField(
                        db_index=True,
                        default=invoicing_app.core.models.generate_uuid,
                        editable=False,
                        help_text="External API reference (UUID4)",
                        max_length=36,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        help_text="Plan name (free, starter, professional, enterprise)",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                            ("past_due", "Past Due"),
                            ("trialing", "Trialing"),
                        ],
                        db_index=True,
                        default="active",
                        help_text="Subscription status",
                        max_length=20,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        auto_now_add=True, help_text="When subscription started"
                    ),
                ),
                (
                    "current_period_start",
                    models.DateField(help_text="Current billing period start"),
                ),
                (
                    "current_period_end",
                    models.DateField(help_text="Current billing period end"),
                ),
                (
                    "trial_end",
                    models.DateField(
                        blank=True,
                        help_text="When trial period ends (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monthly subscription amount in USD",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="Currency code (USD, EUR, GBP, etc.)",
                        max_length=3,
                    ),
                ),
                (
                    "auto_renew",
                    models.BooleanField(
                        default=True,
                        help_text="Auto-renew subscription at end of period",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("credit_card", "Credit Card"),
                            ("debit_card", "Debit Card"),
                            ("bank_transfer", "Bank Transfer"),
                            ("paypal", "PayPal"),
                            ("stripe", "Stripe"),
                        ],
                        default="stripe",
                        help_text="Payment method for renewal",
                        max_length=50,
                    ),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        help_text="Organization this subscription belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "organizations_subscription",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationMember",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.CharField(
                        db_index=True,
                        default=invoicing_app.core.models.generate_uuid,
                        editable=False,
                        help_text="External API reference (UUID4)",
                        max_length=36,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Soft delete flag"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("manager", "Manager"),
                            ("accountant", "Accountant"),
                            ("staff", "Staff"),
                            ("viewer", "Viewer"),
                        ],
                        default="staff",
                        help_text="User's role in this organization",
                        max_length=20,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Is this the primary owner account?"
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When user joined organization"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization this user belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "organizations_member",
                "ordering": ["-is_primary", "-joined_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "user"],
                        name="organizatio_organiz_746f1e_idx",
                    ),
                    models.Index(
                        fields=["organization", "role"],
                        name="organizatio_organiz_a0d450_idx",
                    ),
                ],
                "unique_together": {("organization", "user")},
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.CharField(
                        db_index=True,
                        default=invoicing_app.core.models.generate_uuid,
                        editable=False,
                        help_text="External API reference (UUID4)",
                        max_length=36,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Soft delete flag"
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        db_index=True,
                        help_text="Billing invoice number (e.g., INV-2025-0001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "stripe_invoice_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe Invoice ID",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Invoice amount in cents/dollars",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tax amount",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("issued", "Issued"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Invoice status",
                        max_length=20,
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        auto_now_add=True, help_text="When invoice was issued"
                    ),
                ),
                ("due_date", models.DateField(help_text="Payment due date")),
                (
                    "paid_date",
                    models.DateField(
                        blank=True, help_text="When payment was received", null=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Invoice description/line items",
                        null=True,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization this invoice is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_invoices",
                        to="organizations.organization",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        help_text="Subscription this invoice is for",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="organizations.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "organizations_billing_invoice",
                "ordering": ["-issue_date"],
                "indexes": [
                    models.Index(
                        fields=["organization", "status"],
                        name="organizatio_organiz_faae7a_idx",
                    ),
                    models.Index(
                        fields=["invoice_number"], name="organizatio_invoice_5e5408_idx"
                    ),
                ],
            },
        ),
    ]
