# Generated by Django 5.1 on 2026-04-03 12:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("invoices", "0001_initial"),
        ("organizations", "0001_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialPeriod",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("semi_annual", "Semi-Annual"),
                            ("annual", "Annual"),
                        ],
                        default="monthly",
                        help_text="Type of fiscal period",
                        max_length=20,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(db_index=True, help_text="Period start date"),
                ),
                (
                    "end_date",
                    models.DateField(db_index=True, help_text="Period end date"),
                ),
                (
                    "is_closed",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether period is closed for reporting",
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, help_text="When period was closed", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Period notes", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization this period belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_periods",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "financials_financialperiod",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="RevenueCollection",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "collected_date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Date revenue was collected",
                    ),
                ),
                (
                    "revenue_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Revenue collected (excl. tax)",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tax collected on this revenue",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total collected (revenue + tax)",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "tax_type",
                    models.CharField(
                        default="VAT",
                        help_text="Type of tax (VAT, Withholding, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tax rate applied (%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("collected", "Collected"),
                            ("pending_remittance", "Pending Remittance"),
                            ("remitted", "Remitted"),
                            ("disputed", "Disputed"),
                        ],
                        db_index=True,
                        default="collected",
                        help_text="Revenue/tax status",
                        max_length=20,
                    ),
                ),
                (
                    "remitted_date",
                    models.DateField(
                        blank=True, help_text="Date tax was remitted", null=True
                    ),
                ),
                (
                    "remittance_reference",
                    models.CharField(
                        blank=True,
                        help_text="Tax office remittance reference/receipt",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Collection notes", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "financial_period",
                    models.ForeignKey(
                        help_text="Financial period this revenue belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revenue_collections",
                        to="financials.financialperiod",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        help_text="Invoice this payment is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenue_collections",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization that received payment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenue_collections",
                        to="organizations.organization",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        help_text="Payment that generated this revenue",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenue_collection",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "db_table": "financials_revenuecollection",
                "ordering": ["-collected_date"],
            },
        ),
        migrations.CreateModel(
            name="TaxLiability",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "tax_type",
                    models.CharField(
                        db_index=True,
                        default="VAT",
                        help_text="Type of tax (VAT, Withholding, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total revenue collected in period",
                        max_digits=15,
                    ),
                ),
                (
                    "total_tax_collected",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total tax collected in period",
                        max_digits=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("due_soon", "Due Soon"),
                            ("overdue", "Overdue"),
                            ("remitted", "Remitted"),
                            ("disputed", "Disputed"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Liability status",
                        max_length=20,
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, help_text="Tax remittance due date", null=True
                    ),
                ),
                (
                    "remitted_date",
                    models.DateField(
                        blank=True,
                        help_text="Date tax was actually remitted",
                        null=True,
                    ),
                ),
                (
                    "remittance_reference",
                    models.CharField(
                        blank=True,
                        help_text="Tax office remittance reference/receipt number",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "penalties",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Late payment penalties",
                        max_digits=15,
                    ),
                ),
                (
                    "discounts",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tax credits/discounts",
                        max_digits=15,
                    ),
                ),
                (
                    "final_liability",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Final amount after penalties/discounts",
                        max_digits=15,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Liability notes", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "financial_period",
                    models.ForeignKey(
                        help_text="Financial period this liability covers",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_liabilities",
                        to="financials.financialperiod",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization with tax liability",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_liabilities",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "financials_taxliability",
                "ordering": ["-financial_period", "tax_type"],
            },
        ),
        migrations.AddIndex(
            model_name="financialperiod",
            index=models.Index(
                fields=["organization", "start_date"],
                name="financials__organiz_5c3487_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="financialperiod",
            index=models.Index(
                fields=["organization", "is_closed"],
                name="financials__organiz_cad48a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="financialperiod",
            unique_together={("organization", "start_date", "end_date")},
        ),
        migrations.AddIndex(
            model_name="revenuecollection",
            index=models.Index(
                fields=["organization", "collected_date"],
                name="financials__organiz_9bdffc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="revenuecollection",
            index=models.Index(
                fields=["organization", "status"], name="financials__organiz_06985e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="revenuecollection",
            index=models.Index(
                fields=["organization", "tax_type"],
                name="financials__organiz_a510df_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="revenuecollection",
            index=models.Index(
                fields=["financial_period", "status"],
                name="financials__financi_395229_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="taxliability",
            index=models.Index(
                fields=["organization", "status"], name="financials__organiz_e74e3f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taxliability",
            index=models.Index(
                fields=["organization", "due_date"],
                name="financials__organiz_5c3c90_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taxliability",
            unique_together={("financial_period", "tax_type", "organization")},
        ),
    ]
