# Generated by Django 4.2.28 on 2026-02-15 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Display name (e.g., 'Standard VAT 16%')", max_length=100)),
                ('code', models.CharField(db_index=True, help_text="Unique code (e.g., 'VATX16', 'VATZ00')", max_length=20, unique=True)),
                ('rate_percentage', models.DecimalField(decimal_places=2, help_text='Tax rate as percentage (e.g., 16.00, 0.00)', max_digits=5)),
                ('tax_type', models.CharField(choices=[('vat', 'Value Added Tax (VAT)'), ('income_tax', 'Income Tax'), ('other', 'Other Tax')], db_index=True, default='vat', help_text='Type of tax', max_length=20)),
                ('country', models.CharField(default='Kenya', help_text='Country this rate applies to', max_length=100)),
                ('effective_from', models.DateField(help_text='When this rate becomes effective')),
                ('effective_to', models.DateField(blank=True, db_index=True, help_text='When this rate expires (NULL = still active)', null=True)),
                ('is_vat_applicable', models.BooleanField(default=True, help_text='True if VAT can be recovered on purchases')),
                ('kra_code', models.CharField(blank=True, help_text='KRA eTIMS tax type code (future)', max_length=50, null=True)),
                ('description', models.TextField(blank=True, help_text='Additional details', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'taxes_taxrate',
                'ordering': ['-effective_from', 'code'],
            },
        ),
        migrations.CreateModel(
            name='VATRule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Rule description (e.g., 'Export goods - zero-rated')", max_length=100)),
                ('condition', models.TextField(blank=True, help_text="Future: JSON condition (e.g., 'if customer.country != Kenya')", null=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules evaluated first')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this rule is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tax_class', models.ForeignKey(help_text='Which tax class this rule applies to', on_delete=django.db.models.deletion.CASCADE, related_name='vat_rules', to='products.producttaxclass')),
                ('tax_rate', models.ForeignKey(help_text='Which tax rate to apply', on_delete=django.db.models.deletion.PROTECT, related_name='vat_rules', to='taxes.taxrate')),
            ],
            options={
                'db_table': 'taxes_vatrule',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['code'], name='taxes_taxra_code_e9f5bd_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['tax_type'], name='taxes_taxra_tax_typ_19fc9c_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['effective_from'], name='taxes_taxra_effecti_7b9ffa_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['effective_to'], name='taxes_taxra_effecti_12e87b_idx'),
        ),
        migrations.AddIndex(
            model_name='vatrule',
            index=models.Index(fields=['tax_class'], name='taxes_vatru_tax_cla_94797d_idx'),
        ),
        migrations.AddIndex(
            model_name='vatrule',
            index=models.Index(fields=['tax_rate'], name='taxes_vatru_tax_rat_a5ab89_idx'),
        ),
        migrations.AddIndex(
            model_name='vatrule',
            index=models.Index(fields=['priority'], name='taxes_vatru_priorit_c9ad0e_idx'),
        ),
    ]
