# Generated by Django 4.2.28 on 2026-02-15 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import invoicing_app.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text="Role name, e.g., 'admin', 'accountant'", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Human-readable role description', null=True)),
                ('permissions', models.JSONField(default=list, help_text='List of permission codes this role has')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this role was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this role was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this role is active')),
            ],
            options={
                'db_table': 'user_management_userrole',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='user_manage_name_50aeb6_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_index=True, default=invoicing_app.core.models.generate_uuid, editable=False, help_text='External API reference (UUID4)', max_length=36, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('phone', models.CharField(blank=True, help_text="User's phone number", max_length=20, null=True)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('accountant', 'Accountant'), ('user', 'Regular User')], db_index=True, default='user', help_text="User's role (admin, accountant, user)", max_length=50)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this account (for audit)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to='user_management.customuser')),
                ('user', models.OneToOneField(help_text="Link to Django's built-in User", on_delete=django.db.models.deletion.CASCADE, related_name='invoicing_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_management_customuser',
                'ordering': ['user__email'],
                'indexes': [models.Index(fields=['role'], name='user_manage_role_6457cd_idx'), models.Index(fields=['is_active'], name='user_manage_is_acti_1defd6_idx')],
            },
        ),
    ]
