# Generated by Django 4.2.28 on 2026-02-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('staff', 'Staff'), ('user', 'User')], db_index=True, default='user', help_text="User's role (admin, manager, staff, user)", max_length=50),
        ),
    ]
