# Generated by Django 4.2.28 on 2026-02-25 13:05

from django.db import migrations


def migrate_old_roles(apps, schema_editor):
    """
    Migrate old role values to new role system:
    - 'accountant' → 'manager'
    - 'admin' → 'admin' (no change)
    - other values → 'user' (no change)
    """
    CustomUser = apps.get_model('user_management', 'CustomUser')
    
    # Migrate accountant to manager
    CustomUser.objects.filter(role='accountant').update(role='manager')


def reverse_migrate_roles(apps, schema_editor):
    """Reverse the migration (map back to old roles)"""
    CustomUser = apps.get_model('user_management', 'CustomUser')
    
    # Map manager back to accountant
    CustomUser.objects.filter(role='manager').update(role='accountant')


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.RunPython(migrate_old_roles, reverse_migrate_roles),
    ]
