# Generated by Django 4.2.28 on 2026-02-25 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_migrate_roles_to_new_system'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customuser',
            new_name='user_manage_role_id_18a0e6_idx',
            old_name='user_manage_role_6457cd_idx',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(blank=True, help_text="User's role (dynamically defined)", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='user_management.userrole'),
        ),
    ]
