# Generated by Django 4.2.28 on 2026-02-25 13:23

from django.db import migrations


def create_default_roles(apps, schema_editor):
    """Create default system roles with comprehensive permissions"""
    from invoicing_app.core.permissions import (
        EXPENSE_PERMISSIONS, INVOICE_PERMISSIONS, CLIENT_PERMISSIONS,
        PAYMENT_PERMISSIONS, QUOTATION_PERMISSIONS, USER_PERMISSIONS,
        SYSTEM_PERMISSIONS, REPORT_PERMISSIONS, ALL_PERMISSIONS
    )
    
    UserRole = apps.get_model('user_management', 'UserRole')
    
    # Admin: All permissions
    admin_permissions = list(ALL_PERMISSIONS.keys())
    
    # Manager: High-level access to operations
    manager_permissions = [
        # Expenses
        *['create_expenses', 'view_all_expenses', 'edit_own_expenses', 'delete_own_draft_expenses',
          'submit_expenses', 'approve_expenses', 'mark_expense_paid'],
        # Invoices
        *['create_invoices', 'view_invoices', 'edit_invoices', 'delete_invoices',
          'send_invoices', 'view_invoice_reports'],
        # Clients
        *['manage_clients', 'view_clients', 'view_client_contacts'],
        # Payments
        *['process_payments', 'view_payments', 'manage_payment_methods', 'reconcile_payments'],
        # Quotations
        *['create_quotations', 'view_quotations', 'edit_quotations', 'delete_quotations',
          'convert_quotations'],
        # Users
        *['view_users', 'edit_own_profile'],
        # Reports
        *['view_reports', 'export_reports'],
    ]
    
    # Staff: Standard daily operations
    staff_permissions = [
        # Expenses
        *['create_expenses', 'view_own_expenses', 'edit_own_draft_expenses', 'delete_own_draft_expenses',
          'submit_expenses'],
        # Invoices
        *['create_invoices', 'view_invoices', 'edit_invoices', 'send_invoices'],
        # Clients
        *['manage_clients', 'view_clients', 'view_client_contacts'],
        # Payments
        *['process_payments', 'view_payments'],
        # Quotations
        *['create_quotations', 'view_quotations', 'edit_quotations', 'convert_quotations'],
        # Users
        *['edit_own_profile'],
        # Reports
        *['view_reports', 'export_reports'],
    ]
    
    # User: Read-only access
    user_permissions = [
        # Expenses
        'view_own_expenses',
        # Invoices
        'view_invoices',
        # Clients
        'view_clients',
        # Quotations
        'view_quotations',
        # Users
        'edit_own_profile',
        # Reports
        'view_reports',
    ]
    
    roles_data = [
        {
            'name': 'admin',
            'description': 'Administrator - Full system access with all administrative privileges',
            'permissions': admin_permissions,
        },
        {
            'name': 'manager',
            'description': 'Manager - Elevated access to manage operations and staff',
            'permissions': manager_permissions,
        },
        {
            'name': 'staff',
            'description': 'Staff - Standard access for daily operations',
            'permissions': staff_permissions,
        },
        {
            'name': 'user',
            'description': 'User - Basic read-only access for general users',
            'permissions': user_permissions,
        },
    ]
    
    for role_data in roles_data:
        UserRole.objects.get_or_create(
            name=role_data['name'],
            defaults={
                'description': role_data['description'],
                'permissions': role_data['permissions'],
                'is_active': True,
            }
        )


def delete_default_roles(apps, schema_editor):
    """Delete default roles (reverse migration)"""
    UserRole = apps.get_model('user_management', 'UserRole')
    UserRole.objects.filter(name__in=['admin', 'manager', 'staff', 'user']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_rename_user_manage_role_6457cd_idx_user_manage_role_id_18a0e6_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_roles, delete_default_roles),
    ]
