# Generated by Django 4.2.28 on 2026-02-25 13:25

from django.db import migrations


def assign_default_roles(apps, schema_editor):
    """Assign default 'staff' role to all users without a role"""
    CustomUser = apps.get_model('user_management', 'CustomUser')
    UserRole = apps.get_model('user_management', 'UserRole')
    
    try:
        staff_role = UserRole.objects.get(name='staff')
        # Assign staff role to all users without aRole
        CustomUser.objects.filter(role__isnull=True).update(role=staff_role)
    except UserRole.DoesNotExist:
        # If default roles aren't created yet, skip
        pass


def unassign_roles(apps, schema_editor):
    """Remove roles from users (reverse migration)"""
    CustomUser = apps.get_model('user_management', 'CustomUser')
    CustomUser.objects.all().update(role=None)


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_load_default_roles'),
    ]

    operations = [
        migrations.RunPython(assign_default_roles, unassign_roles),
    ]
