# Generated by Django 5.1 on 2026-04-03 12:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("invoices", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "entity_type",
                    models.CharField(
                        db_index=True,
                        help_text="Entity type (invoice, payment, client, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "entity_id",
                    models.BigIntegerField(help_text="ID of entity modified"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                            ("issued", "Issued"),
                            ("sent", "Sent to Client"),
                            ("viewed", "Viewed by Client"),
                            ("paid", "Marked as Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        help_text="Action taken",
                        max_length=20,
                    ),
                ),
                (
                    "old_values",
                    models.JSONField(
                        blank=True, help_text="Previous values (for updates)", null=True
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(
                        blank=True, help_text="New values (for updates)", null=True
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When change occurred",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of request (for security audit)",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        help_text="Browser/app user agent",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional context", null=True
                    ),
                ),
                (
                    "is_kra_verified",
                    models.BooleanField(
                        default=False, help_text="Has KRA acknowledged this change?"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who made the change",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_auditlog",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="audit_audit_entity__9535bf_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="audit_audit_timesta_19e18a_idx"
                    ),
                    models.Index(
                        fields=["actor"], name="audit_audit_actor_i_17b775_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InvoiceSnapshot",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "invoice_number",
                    models.CharField(
                        db_index=True,
                        help_text="Denormalized invoice number for quick lookup",
                        max_length=50,
                    ),
                ),
                (
                    "snapshot_date",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When this snapshot was taken",
                    ),
                ),
                (
                    "snapshot_version",
                    models.IntegerField(
                        default=1, help_text="Version number (for edited invoices)"
                    ),
                ),
                (
                    "invoice_state_json",
                    models.JSONField(
                        help_text="Full JSON dump of invoice at snapshot time"
                    ),
                ),
                (
                    "kra_etims_receipt",
                    models.TextField(
                        blank=True,
                        help_text="KRA eTIMS receipt/confirmation (future)",
                        null=True,
                    ),
                ),
                (
                    "is_kra_verified",
                    models.BooleanField(
                        default=False, help_text="Has KRA acknowledged this invoice?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.OneToOneField(
                        help_text="Invoice this snapshot is for",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="snapshot",
                        to="invoices.invoice",
                    ),
                ),
            ],
            options={
                "db_table": "audit_invoicesnapshot",
                "ordering": ["-snapshot_date"],
                "indexes": [
                    models.Index(
                        fields=["invoice"], name="audit_invoi_invoice_d58d5b_idx"
                    ),
                    models.Index(
                        fields=["invoice_number"], name="audit_invoi_invoice_acf52e_idx"
                    ),
                    models.Index(
                        fields=["snapshot_date"], name="audit_invoi_snapsho_4105a8_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LoginHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "login_time",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When user logged in",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of login", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        help_text="Browser/device information",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "device_info",
                    models.CharField(
                        blank=True,
                        help_text="Extracted device name (Chrome, Safari, etc.)",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Geographic location (from IP lookup)",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        help_text="Django session ID",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "logout_time",
                    models.DateTimeField(
                        blank=True, help_text="When user logged out", null=True
                    ),
                ),
                (
                    "is_successful",
                    models.BooleanField(
                        default=True, help_text="Whether login was successful"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who logged in",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_loginhistory",
                "ordering": ["-login_time"],
                "indexes": [
                    models.Index(
                        fields=["user", "-login_time"],
                        name="audit_login_user_id_66beb1_idx",
                    ),
                    models.Index(
                        fields=["ip_address"], name="audit_login_ip_addr_a8a782_idx"
                    ),
                    models.Index(
                        fields=["login_time"], name="audit_login_login_t_468d08_idx"
                    ),
                ],
            },
        ),
    ]
