# Generated by Django 4.2.28 on 2026-02-27 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When user logged in')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of login', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Browser/device information', max_length=500, null=True)),
                ('device_info', models.CharField(blank=True, help_text='Extracted device name (Chrome, Safari, etc.)', max_length=200, null=True)),
                ('location', models.CharField(blank=True, help_text='Geographic location (from IP lookup)', max_length=200, null=True)),
                ('session_id', models.CharField(blank=True, help_text='Django session ID', max_length=255, null=True)),
                ('logout_time', models.DateTimeField(blank=True, help_text='When user logged out', null=True)),
                ('is_successful', models.BooleanField(default=True, help_text='Whether login was successful')),
                ('user', models.ForeignKey(help_text='User who logged in', on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_loginhistory',
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['user', '-login_time'], name='audit_login_user_id_66beb1_idx'), models.Index(fields=['ip_address'], name='audit_login_ip_addr_a8a782_idx'), models.Index(fields=['login_time'], name='audit_login_login_t_468d08_idx')],
            },
        ),
    ]
