# Generated by Django 5.1 on 2026-04-03 12:54

import django.db.models.deletion
import django.utils.timezone
import invoicing_app.core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("products", "0001_initial"),
        ("taxes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.CharField(
                        db_index=True,
                        default=invoicing_app.core.models.generate_uuid,
                        editable=False,
                        help_text="External API reference (UUID4)",
                        max_length=36,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Soft delete flag"
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        db_index=True,
                        help_text="Invoice number (e.g., INV-2026-0001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "invoice_date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Invoice date",
                    ),
                ),
                ("due_date", models.DateField(help_text="Payment due date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("issued", "Issued"),
                            ("sent", "Sent to Client"),
                            ("viewed", "Viewed by Client"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Invoice status",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional memo/description", null=True
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("KES", "Kenyan Shilling"), ("USD", "US Dollar")],
                        default="KES",
                        help_text="Invoice currency",
                        max_length=3,
                    ),
                ),
                (
                    "subtotal_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Sum of all line item amounts (excl. VAT)",
                        max_digits=15,
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total VAT on all line items",
                        max_digits=15,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Subtotal + VAT (total to pay)",
                        max_digits=15,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Sum of all payments received",
                        max_digits=15,
                    ),
                ),
                (
                    "amount_due",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total - amount_paid",
                        max_digits=15,
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When invoice was formally issued",
                        null=True,
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, help_text="When PDF was sent to client", null=True
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When client opened email/clicked link",
                        null=True,
                    ),
                ),
                (
                    "first_reminder_sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When first payment reminder was sent",
                        null=True,
                    ),
                ),
                (
                    "second_reminder_sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When second payment reminder was sent",
                        null=True,
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, help_text="When invoice was cancelled", null=True
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(
                        blank=True, help_text="Reason for cancellation", null=True
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, help_text="When invoice was fully paid", null=True
                    ),
                ),
                (
                    "invoice_pdf",
                    models.FileField(
                        blank=True,
                        help_text="Cached PDF file path",
                        null=True,
                        upload_to="invoices/pdfs/",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Client this invoice is for",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="clients.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this invoice",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this invoice",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "invoices_invoice",
                "ordering": ["-invoice_date", "-invoice_number"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceLineItem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "description",
                    models.CharField(
                        help_text="Description (mandatory if product is NULL)",
                        max_length=500,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, help_text="Quantity", max_digits=12
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per unit (excl. VAT)",
                        max_digits=15,
                    ),
                ),
                (
                    "line_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="quantity × unit_price (excl. VAT)",
                        max_digits=15,
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Calculated VAT (line_amount × tax_rate%)",
                        max_digits=15,
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="line_amount + tax_amount (incl. VAT)",
                        max_digits=15,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Line-item-specific notes", null=True
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(default=0, help_text="Display order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        help_text="Invoice this line item belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Product (optional; if NULL, manual line item)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_lines",
                        to="products.product",
                    ),
                ),
                (
                    "tax_rate",
                    models.ForeignKey(
                        help_text="Which tax rate applies to this line",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_line_items",
                        to="taxes.taxrate",
                    ),
                ),
            ],
            options={
                "db_table": "invoices_invoicelineitem",
                "ordering": ["invoice", "sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceNumberSequence",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "prefix",
                    models.CharField(
                        default="OG-INV",
                        help_text="Invoice number prefix (OG-INV, QUOTE, PROFORMA, etc.)",
                        max_length=20,
                    ),
                ),
                ("year", models.IntegerField(help_text="Calendar year")),
                (
                    "next_sequence",
                    models.BigIntegerField(
                        default=1, help_text="Next sequence number to use"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "invoices_invoicenumbersequence",
                "indexes": [
                    models.Index(
                        fields=["prefix", "year"], name="invoices_in_prefix_a60b7e_idx"
                    )
                ],
                "unique_together": {("prefix", "year")},
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["invoice_number"], name="invoices_in_invoice_e6b546_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["client"], name="invoices_in_client__c4d581_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["status"], name="invoices_in_status_cec546_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["invoice_date"], name="invoices_in_invoice_087f87_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["due_date"], name="invoices_in_due_dat_6cc0ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["created_at"], name="invoices_in_created_09931a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["status", "due_date"], name="invoices_in_status_041490_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoicelineitem",
            index=models.Index(
                fields=["invoice"], name="invoices_in_invoice_91407a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoicelineitem",
            index=models.Index(
                fields=["product"], name="invoices_in_product_9a583b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoicelineitem",
            index=models.Index(
                fields=["tax_rate"], name="invoices_in_tax_rat_9a5795_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoicelineitem",
            index=models.Index(
                fields=["invoice", "product"], name="invoices_in_invoice_899aab_idx"
            ),
        ),
    ]
