# Generated by Django 4.2.28 on 2026-02-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_pdf',
            field=models.FileField(blank=True, help_text='Cached PDF file path', null=True, upload_to='invoices/pdfs/'),
        ),
    ]
