# Generated by Django 4.2.28 on 2026-02-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_invoice_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='When invoice was fully paid', null=True),
        ),
    ]
