# Generated by Django 4.2.28 on 2026-02-15 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Payment method name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this method is available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payments_paymentmethod',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='payments_pa_name_4bafbe_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=15)),
                ('payment_date', models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Date payment was received')),
                ('transaction_reference', models.CharField(blank=True, db_index=True, help_text='External reference (M-Pesa ref, cheque number, bank ref)', max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='pending', help_text='Payment status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(help_text='Invoice this payment is for', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='invoices.invoice')),
                ('payment_method', models.ForeignKey(help_text='How was this payment made?', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.paymentmethod')),
                ('recorded_by', models.ForeignKey(blank=True, help_text='User who recorded this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_payment',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReconciliation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount_matched', models.DecimalField(decimal_places=2, help_text='Amount applied from this payment to this invoice', max_digits=15)),
                ('matched_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this reconciliation occurred')),
                ('notes', models.TextField(blank=True, help_text='Reconciliation notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(help_text='Invoice this payment is for', on_delete=django.db.models.deletion.CASCADE, related_name='payment_reconciliations', to='invoices.invoice')),
                ('payment', models.ForeignKey(help_text='Payment being reconciled', on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='payments.payment')),
                ('reconciled_by', models.ForeignKey(blank=True, help_text='User who performed reconciliation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_paymentreconciliation',
                'ordering': ['-matched_at'],
                'indexes': [models.Index(fields=['payment'], name='payments_pa_payment_714a88_idx'), models.Index(fields=['invoice'], name='payments_pa_invoice_804a9c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice'], name='payments_pa_invoice_fcb1dc_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method'], name='payments_pa_payment_33e537_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='payments_pa_payment_1d6e55_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_reference'], name='payments_pa_transac_2dc1cb_idx'),
        ),
    ]
