# Generated by Django 4.2.28 on 2026-02-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, db_index=True, help_text='Receipt number (e.g., REC-2026-0001)', max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='PaymentReceiptNumberSequence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prefix', models.CharField(default='REC', help_text='Payment receipt number prefix (REC, RCPT, etc.)', max_length=20)),
                ('year', models.IntegerField(help_text='Calendar year')),
                ('next_sequence', models.BigIntegerField(default=1, help_text='Next sequence number to use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payments_receiptnumbersequence',
                'indexes': [models.Index(fields=['prefix', 'year'], name='payments_re_prefix_6c072d_idx')],
                'unique_together': {('prefix', 'year')},
            },
        ),
    ]
