# Generated by Django 4.2.28 on 2026-02-17 22:14

from django.db import migrations, transaction
from django.utils import timezone


def backfill_receipt_numbers(apps, schema_editor):
    """Backfill receipt numbers for existing payments."""
    Payment = apps.get_model('payments', 'Payment')
    PaymentReceiptNumberSequence = apps.get_model('payments', 'PaymentReceiptNumberSequence')
    CompanySettings = apps.get_model('core', 'CompanySettings')
    
    # Get the payment prefix from settings
    try:
        settings = CompanySettings.objects.get(pk=1)
        prefix = settings.payment_prefix
    except CompanySettings.DoesNotExist:
        prefix = 'REC'
    
    # Get all payments that don't have receipt numbers
    payments_without_numbers = Payment.objects.filter(receipt_number__isnull=True).order_by('created_at')
    
    if not payments_without_numbers.exists():
        return  # Nothing to do
    
    # Group payments by year
    payments_by_year = {}
    for payment in payments_without_numbers:
        year = payment.payment_date.year
        if year not in payments_by_year:
            payments_by_year[year] = []
        payments_by_year[year].append(payment)
    
    # Process each year's payments
    with transaction.atomic():
        for year, payments in sorted(payments_by_year.items()):
            # Get or create the sequence for this year/prefix
            seq, created = PaymentReceiptNumberSequence.objects.get_or_create(
                prefix=prefix,
                year=year,
                defaults={'next_sequence': 1}
            )
            
            # Assign receipt numbers to payments in order
            for payment in payments:
                current_seq = seq.next_sequence
                receipt_number = f"{prefix}-{year}-{current_seq:04d}"
                
                payment.receipt_number = receipt_number
                payment.save(update_fields=['receipt_number'])
                
                # Increment sequence for next payment
                seq.next_sequence += 1
                seq.save(update_fields=['next_sequence'])


def reverse_backfill(apps, schema_editor):
    """Reverse the backfill by clearing receipt numbers."""
    Payment = apps.get_model('payments', 'Payment')
    Payment.objects.all().update(receipt_number=None)


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_receipt_number_paymentreceiptnumbersequence'),
    ]

    operations = [
        migrations.RunPython(backfill_receipt_numbers, reverse_backfill),
    ]
