# Generated by Django 4.2.28 on 2026-02-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_backfill_payment_receipt_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_pdf',
            field=models.FileField(blank=True, help_text='Generated PDF receipt file', null=True, upload_to='payments/receipts/'),
        ),
    ]
