# Generated by Django 4.2.28 on 2026-02-18 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_receipt_pdf'),
    ]

    operations = [
    ]
