# Generated by Django 5.1 on 2026-04-03 12:54

import django.db.models.deletion
import django.utils.timezone
import invoicing_app.core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("invoices", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Soft delete flag"
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        db_index=True,
                        default=invoicing_app.core.models.generate_uuid,
                        editable=False,
                        help_text="External API reference (UUID4)",
                        max_length=36,
                    ),
                ),
                (
                    "delivery_number",
                    models.CharField(
                        db_index=True,
                        help_text="Delivery challan number (e.g., DLV-2026-0001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Scheduled delivery date",
                    ),
                ),
                (
                    "actual_delivery_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Actual delivery date",
                        null=True,
                    ),
                ),
                (
                    "delivery_time",
                    models.TimeField(
                        blank=True, help_text="Time of delivery", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("in_transit", "In Transit"),
                            ("delivered", "Delivered"),
                            ("partially_delivered", "Partially Delivered"),
                            ("failed", "Delivery Failed"),
                            ("returned", "Returned"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Delivery status",
                        max_length=30,
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Courier/tracking number",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("hand_delivery", "Hand Delivery"),
                            ("courier", "Courier Service"),
                            ("pickup", "Customer Pickup"),
                            ("email", "Email/Digital"),
                            ("other", "Other"),
                        ],
                        default="hand_delivery",
                        help_text="How items are delivered",
                        max_length=50,
                    ),
                ),
                (
                    "delivery_location",
                    models.TextField(
                        blank=True, help_text="Delivery address/location", null=True
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of person receiving delivery",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "recipient_signature_url",
                    models.FileField(
                        blank=True,
                        help_text="Digital signature proof of delivery",
                        null=True,
                        upload_to="deliveries/signatures/",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("good", "Good Condition"),
                            ("damaged", "Damaged"),
                            ("partial", "Partial/Incomplete"),
                            ("not_delivered", "Not Deliverable"),
                        ],
                        default="good",
                        help_text="Condition of items upon delivery",
                        max_length=50,
                    ),
                ),
                (
                    "condition_notes",
                    models.TextField(
                        blank=True,
                        help_text="Details about item condition or issues",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional delivery notes", null=True
                    ),
                ),
                (
                    "delivery_pdf",
                    models.FileField(
                        blank=True,
                        help_text="Generated PDF delivery challan",
                        null=True,
                        upload_to="deliveries/pdfs/",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this delivery",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        help_text="Invoice this delivery is for",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="invoices.invoice",
                    ),
                ),
            ],
            options={
                "db_table": "deliveries_delivery",
                "ordering": ["-delivery_number"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryLineItem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "quantity_scheduled",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantity scheduled for delivery",
                        max_digits=10,
                    ),
                ),
                (
                    "quantity_delivered",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Quantity actually delivered",
                        max_digits=10,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="pcs",
                        help_text="Unit of measurement (pcs, kg, liters, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Item description", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Any notes about this item", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "delivery",
                    models.ForeignKey(
                        help_text="Parent delivery",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="deliveries.delivery",
                    ),
                ),
                (
                    "invoice_line",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related invoice line item",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_items",
                        to="invoices.invoicelineitem",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product being delivered",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "db_table": "deliveries_deliverylineitem",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryNumberSequence",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "prefix",
                    models.CharField(
                        default="DLV",
                        help_text="Delivery number prefix (DLV, CHALLAN, etc.)",
                        max_length=20,
                    ),
                ),
                ("year", models.IntegerField(help_text="Calendar year")),
                (
                    "next_sequence",
                    models.BigIntegerField(
                        default=1, help_text="Next sequence number to use"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "deliveries_deliverynumbersequence",
                "indexes": [
                    models.Index(
                        fields=["prefix", "year"], name="deliveries__prefix_29e89c_idx"
                    )
                ],
                "unique_together": {("prefix", "year")},
            },
        ),
        migrations.AddIndex(
            model_name="delivery",
            index=models.Index(
                fields=["invoice", "status"], name="deliveries__invoice_f9c6cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="delivery",
            index=models.Index(
                fields=["scheduled_date"], name="deliveries__schedul_27722d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="delivery",
            index=models.Index(
                fields=["actual_delivery_date"], name="deliveries__actual__d85fdb_idx"
            ),
        ),
    ]
