# Generated by Django 4.2.28 on 2026-02-15 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import invoicing_app.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTaxClass',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_index=True, default=invoicing_app.core.models.generate_uuid, editable=False, help_text='External API reference (UUID4)', max_length=36, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('name', models.CharField(db_index=True, help_text="Tax class name (e.g., 'Standard VAT', 'Zero-Rated')", max_length=100, unique=True)),
                ('rate_type', models.CharField(choices=[('standard', 'Standard VAT (16%)'), ('zero', 'Zero-Rated (0%)'), ('exempt', 'Exempt (no VAT)')], help_text='Type of VAT treatment', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Product Tax Classes',
                'db_table': 'products_producttaxclass',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='products_pr_name_992049_idx'), models.Index(fields=['rate_type'], name='products_pr_rate_ty_a9f29d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_index=True, default=invoicing_app.core.models.generate_uuid, editable=False, help_text='External API reference (UUID4)', max_length=36, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('name', models.CharField(db_index=True, help_text='Category name (unique)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this category', null=True)),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
                'db_table': 'products_productcategory',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='products_pr_name_863729_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_index=True, default=invoicing_app.core.models.generate_uuid, editable=False, help_text='External API reference (UUID4)', max_length=36, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('sku', models.CharField(db_index=True, help_text='Stock keeping unit (unique)', max_length=100, unique=True)),
                ('name', models.CharField(db_index=True, help_text='Product/service name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description', null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Base price (excluding VAT)', max_digits=15)),
                ('unit', models.CharField(choices=[('piece', 'Piece'), ('kg', 'Kilogram'), ('liter', 'Liter'), ('meter', 'Meter'), ('hour', 'Hour'), ('day', 'Day'), ('service', 'Service'), ('other', 'Other')], default='piece', help_text='Unit of measurement', max_length=20)),
                ('category', models.ForeignKey(blank=True, help_text='Product category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productcategory')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL)),
                ('tax_class', models.ForeignKey(help_text='Default VAT treatment for this product', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.producttaxclass')),
            ],
            options={
                'db_table': 'products_product',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['sku'], name='products_pr_sku_ca0cdc_idx'), models.Index(fields=['name'], name='products_pr_name_9ff0a3_idx'), models.Index(fields=['category'], name='products_pr_categor_9edb3d_idx'), models.Index(fields=['tax_class'], name='products_pr_tax_cla_b5e6f7_idx'), models.Index(fields=['is_active'], name='products_pr_is_acti_ca4d9a_idx')],
            },
        ),
    ]
